DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Sequence;

CREATE TABLE User (
    Id BIGINT(20) NOT NULL AUTO_INCREMENT,
    Username VARCHAR(30) NOT NULL,
    Password VARCHAR(30) NOT NULL,
    CreatedOn DATETIME DEFAULT NULL,
    LastLogin DATETIME DEFAULT NULL,

    PRIMARY KEY (Id)
);

CREATE TABLE Sequence (
  Next_Val BIGINT(20) DEFAULT NULL
);

INSERT INTO Sequence(Next_Val) VALUES (120);